name: todo_list
description: To Do List in Flutter using Firebase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  firebase_ui_auth: ^1.0.5
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5

  image_picker: ^0.8.6
  firebase_ui_localizations: ^1.0.0
  firebase_messaging: ^14.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/1024.png"
  adaptive_icon_background: "#6593f7"
  adaptive_icon_foreground: "assets/icons/1024.png"
